// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqdWg6TxRr4GDXc1FdtVZrYVIRsTsrf4Y',
    appId: '1:57456317138:web:652fff4997a2284b0b930b',
    messagingSenderId: '57456317138',
    projectId: 'luxuryauction-e9c56',
    authDomain: 'luxuryauction-e9c56.firebaseapp.com',
    storageBucket: 'luxuryauction-e9c56.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt9B_Al-73obnLEHE6XVxYI_gCXbImN0I',
    appId: '1:57456317138:android:0fd293e40d4ffb030b930b',
    messagingSenderId: '57456317138',
    projectId: 'luxuryauction-e9c56',
    storageBucket: 'luxuryauction-e9c56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOkj7kVTPLoYbCH1aSTpT52NBV3Q76xzo',
    appId: '1:57456317138:ios:f3f972839887a0040b930b',
    messagingSenderId: '57456317138',
    projectId: 'luxuryauction-e9c56',
    storageBucket: 'luxuryauction-e9c56.firebasestorage.app',
    iosBundleId: 'com.example.luxuryAuctionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOkj7kVTPLoYbCH1aSTpT52NBV3Q76xzo',
    appId: '1:57456317138:ios:f3f972839887a0040b930b',
    messagingSenderId: '57456317138',
    projectId: 'luxuryauction-e9c56',
    storageBucket: 'luxuryauction-e9c56.firebasestorage.app',
    iosBundleId: 'com.example.luxuryAuctionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqdWg6TxRr4GDXc1FdtVZrYVIRsTsrf4Y',
    appId: '1:57456317138:web:ecba537ec862dec00b930b',
    messagingSenderId: '57456317138',
    projectId: 'luxuryauction-e9c56',
    authDomain: 'luxuryauction-e9c56.firebaseapp.com',
    storageBucket: 'luxuryauction-e9c56.firebasestorage.app',
  );
}
