/// Country code (ISO 3166-1 alpha-2) and display name for nationality picker.
class CountryEntry {
  const CountryEntry({required this.code, required this.name});
  final String code;
  final String name;
}

/// Full list of countries (ISO 3166-1 alpha-2) for KYC nationality field.
/// Sorted by name for searchable picker.
const List<CountryEntry> kCountries = [
  CountryEntry(code: 'AF', name: 'Afghanistan'),
  CountryEntry(code: 'AL', name: 'Albania'),
  CountryEntry(code: 'DZ', name: 'Algeria'),
  CountryEntry(code: 'AD', name: 'Andorra'),
  CountryEntry(code: 'AO', name: 'Angola'),
  CountryEntry(code: 'AG', name: 'Antigua and Barbuda'),
  CountryEntry(code: 'AR', name: 'Argentina'),
  CountryEntry(code: 'AM', name: 'Armenia'),
  CountryEntry(code: 'AU', name: 'Australia'),
  CountryEntry(code: 'AT', name: 'Austria'),
  CountryEntry(code: 'AZ', name: 'Azerbaijan'),
  CountryEntry(code: 'BS', name: 'Bahamas'),
  CountryEntry(code: 'BH', name: 'Bahrain'),
  CountryEntry(code: 'BD', name: 'Bangladesh'),
  CountryEntry(code: 'BB', name: 'Barbados'),
  CountryEntry(code: 'BY', name: 'Belarus'),
  CountryEntry(code: 'BE', name: 'Belgium'),
  CountryEntry(code: 'BZ', name: 'Belize'),
  CountryEntry(code: 'BJ', name: 'Benin'),
  CountryEntry(code: 'BT', name: 'Bhutan'),
  CountryEntry(code: 'BO', name: 'Bolivia'),
  CountryEntry(code: 'BA', name: 'Bosnia and Herzegovina'),
  CountryEntry(code: 'BW', name: 'Botswana'),
  CountryEntry(code: 'BR', name: 'Brazil'),
  CountryEntry(code: 'BN', name: 'Brunei'),
  CountryEntry(code: 'BG', name: 'Bulgaria'),
  CountryEntry(code: 'BF', name: 'Burkina Faso'),
  CountryEntry(code: 'BI', name: 'Burundi'),
  CountryEntry(code: 'CV', name: 'Cabo Verde'),
  CountryEntry(code: 'KH', name: 'Cambodia'),
  CountryEntry(code: 'CM', name: 'Cameroon'),
  CountryEntry(code: 'CA', name: 'Canada'),
  CountryEntry(code: 'CF', name: 'Central African Republic'),
  CountryEntry(code: 'TD', name: 'Chad'),
  CountryEntry(code: 'CL', name: 'Chile'),
  CountryEntry(code: 'CN', name: 'China'),
  CountryEntry(code: 'CO', name: 'Colombia'),
  CountryEntry(code: 'KM', name: 'Comoros'),
  CountryEntry(code: 'CG', name: 'Congo'),
  CountryEntry(code: 'CD', name: 'Congo (Democratic Republic)'),
  CountryEntry(code: 'CR', name: 'Costa Rica'),
  CountryEntry(code: 'HR', name: 'Croatia'),
  CountryEntry(code: 'CU', name: 'Cuba'),
  CountryEntry(code: 'CY', name: 'Cyprus'),
  CountryEntry(code: 'CZ', name: 'Czech Republic'),
  CountryEntry(code: 'DK', name: 'Denmark'),
  CountryEntry(code: 'DJ', name: 'Djibouti'),
  CountryEntry(code: 'DM', name: 'Dominica'),
  CountryEntry(code: 'DO', name: 'Dominican Republic'),
  CountryEntry(code: 'EC', name: 'Ecuador'),
  CountryEntry(code: 'EG', name: 'Egypt'),
  CountryEntry(code: 'SV', name: 'El Salvador'),
  CountryEntry(code: 'GQ', name: 'Equatorial Guinea'),
  CountryEntry(code: 'ER', name: 'Eritrea'),
  CountryEntry(code: 'EE', name: 'Estonia'),
  CountryEntry(code: 'SZ', name: 'Eswatini'),
  CountryEntry(code: 'ET', name: 'Ethiopia'),
  CountryEntry(code: 'FJ', name: 'Fiji'),
  CountryEntry(code: 'FI', name: 'Finland'),
  CountryEntry(code: 'FR', name: 'France'),
  CountryEntry(code: 'GA', name: 'Gabon'),
  CountryEntry(code: 'GM', name: 'Gambia'),
  CountryEntry(code: 'GE', name: 'Georgia'),
  CountryEntry(code: 'DE', name: 'Germany'),
  CountryEntry(code: 'GH', name: 'Ghana'),
  CountryEntry(code: 'GR', name: 'Greece'),
  CountryEntry(code: 'GD', name: 'Grenada'),
  CountryEntry(code: 'GT', name: 'Guatemala'),
  CountryEntry(code: 'GN', name: 'Guinea'),
  CountryEntry(code: 'GW', name: 'Guinea-Bissau'),
  CountryEntry(code: 'GY', name: 'Guyana'),
  CountryEntry(code: 'HT', name: 'Haiti'),
  CountryEntry(code: 'HN', name: 'Honduras'),
  CountryEntry(code: 'HK', name: 'Hong Kong'),
  CountryEntry(code: 'HU', name: 'Hungary'),
  CountryEntry(code: 'IS', name: 'Iceland'),
  CountryEntry(code: 'IN', name: 'India'),
  CountryEntry(code: 'ID', name: 'Indonesia'),
  CountryEntry(code: 'IR', name: 'Iran'),
  CountryEntry(code: 'IQ', name: 'Iraq'),
  CountryEntry(code: 'IE', name: 'Ireland'),
  CountryEntry(code: 'IL', name: 'Israel'),
  CountryEntry(code: 'IT', name: 'Italy'),
  CountryEntry(code: 'CI', name: 'Ivory Coast'),
  CountryEntry(code: 'JM', name: 'Jamaica'),
  CountryEntry(code: 'JP', name: 'Japan'),
  CountryEntry(code: 'JO', name: 'Jordan'),
  CountryEntry(code: 'KZ', name: 'Kazakhstan'),
  CountryEntry(code: 'KE', name: 'Kenya'),
  CountryEntry(code: 'KI', name: 'Kiribati'),
  CountryEntry(code: 'KP', name: 'North Korea'),
  CountryEntry(code: 'KR', name: 'South Korea'),
  CountryEntry(code: 'KW', name: 'Kuwait'),
  CountryEntry(code: 'KG', name: 'Kyrgyzstan'),
  CountryEntry(code: 'LA', name: 'Laos'),
  CountryEntry(code: 'LV', name: 'Latvia'),
  CountryEntry(code: 'LB', name: 'Lebanon'),
  CountryEntry(code: 'LS', name: 'Lesotho'),
  CountryEntry(code: 'LR', name: 'Liberia'),
  CountryEntry(code: 'LY', name: 'Libya'),
  CountryEntry(code: 'LI', name: 'Liechtenstein'),
  CountryEntry(code: 'LT', name: 'Lithuania'),
  CountryEntry(code: 'LU', name: 'Luxembourg'),
  CountryEntry(code: 'MO', name: 'Macau'),
  CountryEntry(code: 'MG', name: 'Madagascar'),
  CountryEntry(code: 'MW', name: 'Malawi'),
  CountryEntry(code: 'MY', name: 'Malaysia'),
  CountryEntry(code: 'MV', name: 'Maldives'),
  CountryEntry(code: 'ML', name: 'Mali'),
  CountryEntry(code: 'MT', name: 'Malta'),
  CountryEntry(code: 'MH', name: 'Marshall Islands'),
  CountryEntry(code: 'MR', name: 'Mauritania'),
  CountryEntry(code: 'MU', name: 'Mauritius'),
  CountryEntry(code: 'MX', name: 'Mexico'),
  CountryEntry(code: 'FM', name: 'Micronesia'),
  CountryEntry(code: 'MD', name: 'Moldova'),
  CountryEntry(code: 'MC', name: 'Monaco'),
  CountryEntry(code: 'MN', name: 'Mongolia'),
  CountryEntry(code: 'ME', name: 'Montenegro'),
  CountryEntry(code: 'MA', name: 'Morocco'),
  CountryEntry(code: 'MZ', name: 'Mozambique'),
  CountryEntry(code: 'MM', name: 'Myanmar'),
  CountryEntry(code: 'NA', name: 'Namibia'),
  CountryEntry(code: 'NR', name: 'Nauru'),
  CountryEntry(code: 'NP', name: 'Nepal'),
  CountryEntry(code: 'NL', name: 'Netherlands'),
  CountryEntry(code: 'NZ', name: 'New Zealand'),
  CountryEntry(code: 'NI', name: 'Nicaragua'),
  CountryEntry(code: 'NE', name: 'Niger'),
  CountryEntry(code: 'NG', name: 'Nigeria'),
  CountryEntry(code: 'MK', name: 'North Macedonia'),
  CountryEntry(code: 'NO', name: 'Norway'),
  CountryEntry(code: 'OM', name: 'Oman'),
  CountryEntry(code: 'PK', name: 'Pakistan'),
  CountryEntry(code: 'PW', name: 'Palau'),
  CountryEntry(code: 'PS', name: 'Palestine'),
  CountryEntry(code: 'PA', name: 'Panama'),
  CountryEntry(code: 'PG', name: 'Papua New Guinea'),
  CountryEntry(code: 'PY', name: 'Paraguay'),
  CountryEntry(code: 'PE', name: 'Peru'),
  CountryEntry(code: 'PH', name: 'Philippines'),
  CountryEntry(code: 'PL', name: 'Poland'),
  CountryEntry(code: 'PT', name: 'Portugal'),
  CountryEntry(code: 'QA', name: 'Qatar'),
  CountryEntry(code: 'RO', name: 'Romania'),
  CountryEntry(code: 'RU', name: 'Russia'),
  CountryEntry(code: 'RW', name: 'Rwanda'),
  CountryEntry(code: 'KN', name: 'Saint Kitts and Nevis'),
  CountryEntry(code: 'LC', name: 'Saint Lucia'),
  CountryEntry(code: 'VC', name: 'Saint Vincent and the Grenadines'),
  CountryEntry(code: 'WS', name: 'Samoa'),
  CountryEntry(code: 'SM', name: 'San Marino'),
  CountryEntry(code: 'ST', name: 'Sao Tome and Principe'),
  CountryEntry(code: 'SA', name: 'Saudi Arabia'),
  CountryEntry(code: 'SN', name: 'Senegal'),
  CountryEntry(code: 'RS', name: 'Serbia'),
  CountryEntry(code: 'SC', name: 'Seychelles'),
  CountryEntry(code: 'SL', name: 'Sierra Leone'),
  CountryEntry(code: 'SG', name: 'Singapore'),
  CountryEntry(code: 'SK', name: 'Slovakia'),
  CountryEntry(code: 'SI', name: 'Slovenia'),
  CountryEntry(code: 'SB', name: 'Solomon Islands'),
  CountryEntry(code: 'SO', name: 'Somalia'),
  CountryEntry(code: 'ZA', name: 'South Africa'),
  CountryEntry(code: 'SS', name: 'South Sudan'),
  CountryEntry(code: 'ES', name: 'Spain'),
  CountryEntry(code: 'LK', name: 'Sri Lanka'),
  CountryEntry(code: 'SD', name: 'Sudan'),
  CountryEntry(code: 'SR', name: 'Suriname'),
  CountryEntry(code: 'SE', name: 'Sweden'),
  CountryEntry(code: 'CH', name: 'Switzerland'),
  CountryEntry(code: 'SY', name: 'Syria'),
  CountryEntry(code: 'TW', name: 'Taiwan'),
  CountryEntry(code: 'TJ', name: 'Tajikistan'),
  CountryEntry(code: 'TZ', name: 'Tanzania'),
  CountryEntry(code: 'TH', name: 'Thailand'),
  CountryEntry(code: 'TL', name: 'Timor-Leste'),
  CountryEntry(code: 'TG', name: 'Togo'),
  CountryEntry(code: 'TO', name: 'Tonga'),
  CountryEntry(code: 'TT', name: 'Trinidad and Tobago'),
  CountryEntry(code: 'TN', name: 'Tunisia'),
  CountryEntry(code: 'TR', name: 'Turkey'),
  CountryEntry(code: 'TM', name: 'Turkmenistan'),
  CountryEntry(code: 'TV', name: 'Tuvalu'),
  CountryEntry(code: 'UG', name: 'Uganda'),
  CountryEntry(code: 'UA', name: 'Ukraine'),
  CountryEntry(code: 'AE', name: 'United Arab Emirates'),
  CountryEntry(code: 'GB', name: 'United Kingdom'),
  CountryEntry(code: 'US', name: 'United States'),
  CountryEntry(code: 'UY', name: 'Uruguay'),
  CountryEntry(code: 'UZ', name: 'Uzbekistan'),
  CountryEntry(code: 'VU', name: 'Vanuatu'),
  CountryEntry(code: 'VA', name: 'Vatican City'),
  CountryEntry(code: 'VE', name: 'Venezuela'),
  CountryEntry(code: 'VN', name: 'Vietnam'),
  CountryEntry(code: 'YE', name: 'Yemen'),
  CountryEntry(code: 'ZM', name: 'Zambia'),
  CountryEntry(code: 'ZW', name: 'Zimbabwe'),
];
